"""Add message model

Revision ID: b5316d59b257
Revises: 2f44b733485a
Create Date: 2025-06-19 11:47:02.890992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5316d59b257'
down_revision = '2f44b733485a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
